### ISSUE TITLE
<shairplay/dnssd.h> file not found

### ISSUE THREAD

**Issue by sunyazhou13** [qasim/Airstream#4]
file cloudn't found

**Comment by qasim** [comment]
@sunyazhou13 did you use Carthage to include the project, or did you clone the repository and add it that way?

I'm able to build as long as I follow the following steps:

1. Create a new Xcode project.
2. Add a `Cartfile` in the same directory as my new project's `<Project name>.xcodeproj`.
3. Add `github "qasim/Airstream"` as a line in the `Cartfile`.
4. Run `carthage update` in a terminal, where your `Cartfile` is located.
5. Wait for `Airstream.framework` to be built, and then add drag `Airstream.framework` from the `Carthage/Builds/Mac` or `Carthage/Builds/iOS` directory into your project, depending on which platform you are making your app for.
6. In your project's settings, go to your project's target settings. Under `Embedded binaries`, add the `Airstream.framework` you just dragged in from the sidebar.

Let me know if that helps!

**Comment by hjqiaho** [comment]
Dependency "shairplay" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/qasim/shairplay/issues/new

==why==
