### ISSUE TITLE
Audio stuttering

### ISSUE THREAD

**Issue by stephengilroy** [qasim/Airstream#5]
I've been playing around with the framework for the last few days and I've noticed a lot of stuttering when streaming audio. I've tried it on two different networks with the same issue, so I don't think it's network related. Pausing/Playing doesn't seem to do anything.

Does this have something to do with the buffer size being used? I frequently use Airplay on my Apple TV without any issues.

**Comment by qasim** [comment]
@stephengilroy Airstream is actually just a framework around AirPlay, and doesn't do any buffering or audio output to speakers for you. Are you talking about the examples?

It's up to the developer to implement smart buffering techniques to reduce stutter from the audio stream. Some strategies can involve slowing down the audio sampling rate slightly (within a few percent of the original speed) when the buffer is running low, to let the network catch up.

**Comment by stephengilroy** [comment]
Oops. Yeah I should've mentioned it was in the examples. Guess I'm going to have to learn more about buffering haha.

**Comment by qasim** [comment]
@stephengilroy It's definitely very interesting and difficult problem. :) I'm also learning as well. If you come up with something that you're happy with, don't hesitate to submit a pull request to one of the example projects.
